# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 主页
    url: '#about'
    weight: 10
  - name: 科研
    url: '#research'
    weight: 20
  - name: 论文
    url: '#publications'
    weight: 30
  - name: 工作
    url: '#work'
    weight: 40
  - name: 奖项
    url: '#awards'
    weight: 50
  - name: 联系方式
    url: '#contact'
    weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
